site_name: Rodolfo Cabral Neves
theme:
  name: material
markdown_extensions:
  - attr_list
  - md_in_html
nav:
  - Home: index.md
  - Software Engineering:
    - Hard Skills: swe/swe_hard_skills.md
    - Experiences: swe/swe_projects.md
    - Courses: swe/swe_courses.md
  - CyberSecurity:
    - Hard Skills: cybersec/cybersec_curriculum.md
    - Experiences: cybersec/cybersec_projects.md
    - Courses and Experiences: cybersec/cybersec_projects.md
  - Open Source contributions: opensource.md
  - Soft Skills: softskills.md